export const sourceNotes = [
  {
    title: '一支烟花AI社区介绍',
    type: '墨问公开 meta',
    status: '可公开读取标题、作者和摘要',
    url: 'https://note.mowen.cn/detail/mQcaY_6GxndRz6_g8m5Uw?code=jc1ShFKLB7tkan9v',
    summary:
      '公开摘要显示社区成立于 2023 年底，核心成员具备互联网与技术背景。本页只引用公开 meta 层信息。',
  },
  {
    title: '21 首次公开！一支烟花社区背后的运营思考',
    type: '墨问公开 meta',
    status: '可公开读取标题、作者和摘要',
    url: 'https://note.mowen.cn/detail/zJ8qV_BZUOjyvkRfwXytU',
    summary:
      '公开摘要强调社区定位、用户留存、差异化策略和 AI 社区建设方法。',
  },
  {
    title: '社区社群介绍',
    type: '飞书文档',
    status: '当前返回登录页，未直接引用正文',
    url: 'https://hqexj12b0g.feishu.cn/docx/TyymdoAdRodWGJxCi6FcJvEUn2b',
    summary:
      '作为加入社区和内部介绍入口保留链接；公开页面不写入不可验证正文。',
  },
  {
    title: '公众号：一支烟花 AI',
    type: '用户提供截图',
    status: '用于展示公开主页信息和二维码',
    url: '#official-account',
    summary:
      '公众号主页显示其专注硬核 AI 内容，包含原创内容数量、视频号入口和扫码关注二维码。',
  },
];

export const projectStats = {
  repos: 19,
  stars: '9,000+',
  forks: '800+',
  updatedAt: '2026-07-05',
  source: 'GitHub REST API / yizhiyanhua-ai public repositories',
};

export const officialAccount = {
  name: '一支烟花 AI',
  location: '上海 长宁',
  tagline: '专注硬核 AI 内容，高质量 AI 洞见独一无二的一支烟花 AI 社区一群有极客精神的 AI 人',
  videoChannel: '一支烟花 AI',
  originalPosts: 223,
  source: '公众号主页截图，用户提供于 2026-07-06',
  qrImage: '/fireworks/assets/wechat-qrcode.jpg',
  profileImage: '/fireworks/assets/wechat-content-preview.jpg',
};

export const wechatArticles = [
  {
    id: 'gemini3-product-sample',
    title: 'Gemini3 首测！游戏、网页、设计、3D、动画制作...超出期待！',
    date: '2025-11-19',
    category: '烟花拆产品',
    summary: '用可运行样本拆 Gemini3 在游戏、网页、设计和 3D 动画里的真实产品感。',
    url: 'https://mp.weixin.qq.com/s/gvdZjCZ8xD4OTV2iRy3F7g',
    source: '公众号原文',
  },
  {
    id: 'deepseek-rl-diagram',
    title: '用流程图对比 DeepSeek-R1、OpenAI o1、Claude',
    date: '2025-01',
    category: '模型基础',
    summary: '用流程图解释强化学习在大模型训练、推理阶段的创新和意义。',
    url: 'https://mp.weixin.qq.com/s/mdGtOcg1Ru-QOEBn31KhxQ',
    source: '公众号原文',
  },
  {
    id: 'agent-replaces-saas',
    title: '微软 CEO 的大胆预言：“AI Agent 将替代所有 SaaS”',
    date: '2024-12-26',
    category: 'Agent 产品',
    summary: '从 Nadella 的判断切入，讨论 Agent 如何重写 SaaS、数据库与业务逻辑的关系。',
    url: 'https://www.doit.com.cn/p/526454.html',
    source: '公开转载',
  },
  {
    id: 'agent-war-2025',
    title: '2025 下半程，Agent War 正式开打！刺刀已然见红！',
    date: '2025-05-13',
    category: 'Agent 战场',
    summary: '观察 Agent 产品竞争进入下半场后，模型、工作流和交付体验如何重新洗牌。',
    url: 'https://weixin.sogou.com/weixin?type=2&query=2025%E4%B8%8B%E5%8D%8A%E7%A8%8B%20Agent%20War%E6%AD%A3%E5%BC%8F%E5%BC%80%E6%89%93%20%E4%B8%80%E6%94%AF%E7%83%9F%E8%8A%B1AI',
    source: '搜索原文',
  },
  {
    id: 'harness-open-source',
    title: '一次 Harness 工程实践，我把它开源出来了！',
    date: '2026-03-28',
    category: '开源实践',
    summary: '把 Claude Code 长任务里的重复错误，沉淀成可复用的 harness 和技能记忆机制。',
    url: 'https://weixin.sogou.com/weixin?type=2&query=%E4%B8%80%E6%AC%A1Harness%E5%B7%A5%E7%A8%8B%E5%AE%9E%E8%B7%B5%20%E6%88%91%E6%8A%8A%E5%AE%83%E5%BC%80%E6%BA%90%E5%87%BA%E6%9D%A5%E4%BA%86%20%E4%B8%80%E6%94%AF%E7%83%9F%E8%8A%B1AI',
    source: '搜索原文',
  },
  {
    id: 'gpt-heart-600-lines',
    title: '600 行代码，读懂 GPT 的心脏',
    date: '2026-04-08',
    category: '模型原理',
    summary: '用更低门槛的代码视角拆开 GPT 结构，让模型原理变成能读懂的工程对象。',
    url: 'https://weixin.sogou.com/weixin?type=2&query=600%E8%A1%8C%E4%BB%A3%E7%A0%81%20%E8%AF%BB%E6%87%82GPT%E7%9A%84%E5%BF%83%E8%84%8F%20%E4%B8%80%E6%94%AF%E7%83%9F%E8%8A%B1AI',
    source: '搜索原文',
  },
  {
    id: 'llm-knowledge-base',
    title: '使用 LLM 构建个人知识库的最佳实践',
    date: '2026-04-03',
    category: '知识系统',
    summary: '把资料、笔记和模型能力组织成可持续生长的个人知识库，而不是一次性问答。',
    url: 'https://weixin.sogou.com/weixin?type=2&query=%E4%BD%BF%E7%94%A8LLM%E6%9E%84%E5%BB%BA%E4%B8%AA%E4%BA%BA%E7%9F%A5%E8%AF%86%E5%BA%93%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%20%E4%B8%80%E6%94%AF%E7%83%9F%E8%8A%B1AI',
    source: '搜索原文',
  },
  {
    id: 'karpathy-code-agents',
    title: 'Andrej Karpathy 最新访谈：Code Agents、AutoResearch 与自我闭环',
    date: '2026-03-24',
    category: '研究观察',
    summary: '围绕 Code Agents、AutoResearch 和 AI 自我闭环能力，梳理下一阶段工具边界。',
    url: 'https://weixin.sogou.com/weixin?type=2&query=Andrej%20Karpathy%20Code%20Agents%20AutoResearch%20%E4%B8%80%E6%94%AF%E7%83%9F%E8%8A%B1AI',
    source: '搜索原文',
  },
];

export const xFeedFallback = {
  account: {
    name: '烟花老师',
    handle: 'teach_fireworks',
    url: 'https://x.com/teach_fireworks',
  },
  updatedAt: '2026-07-07T00:00:00+08:00',
  posts: [
    {
      id: '2050190799837741377',
      url: 'https://x.com/teach_fireworks/status/2050190799837741377',
      createdAt: '本地归档',
      text: 'AI coding 的竞争，开始从模型能力竞争，转向 Agent 工作流竞争。长任务、少打断、并行推进和真实交付，正在变成新的产品分水岭。',
      tags: ['Codex', 'Claude Code', 'Agent Workflow'],
      metrics: 'X archive',
    },
    {
      id: '2048755403220197455',
      url: 'https://x.com/teach_fireworks/status/2048755403220197455',
      createdAt: '本地归档',
      text: '高频用户真正痛的不是“写不出来”，而是 Agent 已经走在正确轨道上时，总被授权、确认、上下文断点打断。',
      tags: ['Long Tasks', 'Developer UX', 'Agent Infra'],
      metrics: 'X archive',
    },
    {
      id: '2048753266637570474',
      url: 'https://x.com/teach_fireworks/status/2048753266637570474',
      createdAt: '本地归档',
      text: '一旦进入多任务并行，单账号、单线程、单终端体验就会变成瓶颈。Coding agent 正在从助手变成工作系统。',
      tags: ['Parallel Agents', 'Worktree', 'Workflow'],
      metrics: 'X archive',
    },
    {
      id: '2051236094352793753',
      url: 'https://x.com/teach_fireworks/status/2051236094352793753',
      createdAt: '本地归档',
      text: 'Goals 不是一个小功能，而是长任务委托的入口。真正重要的是任务能否跨 session 持续、自己验证，并在完成条件满足时停下来。',
      tags: ['Goals', 'Verification', 'Automation'],
      metrics: 'X archive',
    },
  ],
};

export const contentTracks = [
  {
    title: 'Agent 与 AI 产品',
    body: '追踪 Agentic Thinking、Agent Wars、AI 原生产品和 SaaS 替代路径，关注产品判断与真实落地。',
    accent: 'orange',
  },
  {
    title: 'RAG / Memory / 基础设施',
    body: '拆解 RAG、Paged Attention、长期记忆、模型基础设施与工程架构，把论文和实践连起来。',
    accent: 'blue',
  },
  {
    title: 'AI 创业与商业化',
    body: '观察 Anthropic、微软、垂直 AI 产品和增长机制，讨论技术如何进入真实业务。',
    accent: 'gold',
  },
  {
    title: '开源工具与共创项目',
    body: '从文章里的问题出发，沉淀脚本、Skill、演示站点和开源仓库，让内容继续变成工具。',
    accent: 'green',
  },
];

export const communityIntro = {
  founded: '2023 年底',
  headline: '一支烟花 AI，是硬核 AI 内容与共创实验室。',
  body:
    '社区从公众号的深度内容、GitHub 开源项目和社群共创出发，长期关注 AI 产品、Agent、模型基础设施、开源工具和真实落地案例。每一次观察、复盘和实验，都尽量沉淀成下一位实践者可以复用的公开资产。',
  notes: [
    {
      label: '定位',
      value: '硬核 AI 内容 + 开源项目 + 学习共创',
    },
    {
      label: '方法',
      value: '用真实问题驱动文章、工具、教程和演示站点',
    },
    {
      label: '边界',
      value: '公开内容优先，不暴露私密群聊、个人隐私和未授权资料',
    },
  ],
};

export const communityBeliefs = [
  {
    title: '让 AI 学习从信息消费走向作品生产',
    body: '关注能跑起来的脚本、Skill、工作流和复盘，而不只停留在观点和资讯。',
  },
  {
    title: '让个人经验变成团队可以继承的资产',
    body: '把方法写进 README、图谱、模板、演示站点和可验证的开源项目。',
  },
  {
    title: '让社区运营回到真实用户和长期留存',
    body: '重视定位、差异化、用户需求和持续参与，而不是短期流量热闹。',
  },
];

export const featuredProjects = [
  {
    name: 'fireworks-tech-graph',
    category: 'AI 创作与表达',
    productType: 'Technical Visual AI',
    tagline: 'Prompt-to-diagram 技术图生成器',
    useCase: '架构评审 / 云部署 / 事件流 / 可观测性 / Agent 系统',
    outcome: '把自然语言里的工程系统，直接变成几何安全、可校验、可交互的技术图。',
    launchRank: '#1',
    upvotes: '8.3k',
    previewType: 'diagram',
    previewImage: '/fireworks/assets/product-tech-graph-cloud-fabric.png',
    previewAlt: 'fireworks-tech-graph Style 10 Cloud Fabric 主动双活部署图',
    previewSource: 'v1.1.0 sample: Style 10 Cloud Fabric',
    highlights: ['12 种差异化视觉风格', '线束与文字出框自动校验', 'C4 / 云部署 / 事件流 / SRE 语义契约'],
    description:
      '用自然语言生成通过几何与工程语义门禁的技术图，覆盖 12 种独立场景，并支持 SVG、PNG 与离线交互 HTML 多格式输出。',
    url: 'https://github.com/yizhiyanhua-ai/fireworks-tech-graph',
    demo: 'https://yizhiyanhua-ai.github.io/fireworks-tech-graph/',
    stars: 8721,
    forks: 748,
    language: 'Python',
    tags: ['AI diagrams', 'Engineering semantics', 'Interactive HTML'],
    accent: 'blue',
    flagship: true,
  },
  {
    name: 'fireworks-design',
    category: 'AI 创作与表达',
    productType: 'Multi-agent Design Studio',
    tagline: '多 Agent 前端设计工作台',
    useCase: '前端页面生成 / 多方向探索 / 设计评审',
    outcome: '把“想做一个页面”升级成多 Agent 并行探索、评审、融合和对抗打磨的设计流水线。',
    launchRank: '#2',
    upvotes: '48',
    previewType: 'design',
    previewImage: '/fireworks/assets/product-fireworks-design-pipeline.svg',
    previewAlt: 'fireworks-design README 中的六阶段工作流图',
    previewSource: 'README workflow: Six-phase pipeline',
    highlights: ['多方向并行探索', '面板评审与融合', '页面生成工作流'],
    description:
      'Claude Code 工作流：多方向探索、面板评审、融合与对抗打磨，生成高质量前端页面。',
    url: 'https://github.com/yizhiyanhua-ai/fireworks-design',
    demo: 'https://yizhiyanhua-ai.github.io/fireworks-design/',
    stars: 82,
    forks: 3,
    language: 'HTML',
    tags: ['Frontend', 'Multi-agent', 'Design system'],
    accent: 'purple',
    flagship: true,
  },
  {
    name: 'fireworks-skill-memory',
    category: 'AI 记忆与知识系统',
    productType: 'Skill Memory OS',
    tagline: '让 AI 工具越用越懂你',
    useCase: '技能记忆 / 经验复用 / 跨会话上下文',
    outcome: '让 Claude Code 与 Codex Skills 沉淀按技能分层的经验，减少重复探索。',
    launchRank: '#3',
    upvotes: '92',
    previewType: 'memory',
    previewImage: '/fireworks/assets/product-skill-memory-architecture.svg',
    previewAlt: 'fireworks-skill-memory README 中的双运行时共享记忆架构图',
    previewSource: 'README diagram: Dual runtime architecture',
    highlights: ['技能分层记忆', '跨会话复用', 'Codex / Claude Code 友好'],
    description:
      '为 Claude Code 与 Codex Skills 提供按技能分层的持久化经验记忆，让工具越用越懂上下文。',
    url: 'https://github.com/yizhiyanhua-ai/fireworks-skill-memory',
    demo: 'https://yizhiyanhua-ai.github.io/fireworks-skill-memory/',
    stars: 92,
    forks: 7,
    language: 'Python',
    tags: ['Memory', 'Skills', 'Codex'],
    accent: 'green',
  },
  {
    name: 'fireworks-ai-tools-memory',
    category: 'AI 记忆与知识系统',
    productType: 'Tools Memory Layer',
    tagline: 'AI 工具链的长期工作记忆',
    useCase: 'CLI 工具记忆 / 工作流复用 / 知识库',
    outcome: '把 AI 工具、CLI 命令和脚本经验保存成跨会话可检索的工作记忆。',
    launchRank: '#4',
    upvotes: 'New',
    previewType: 'tools',
    previewImage: '/fireworks/assets/product-tools-memory-landing.webp',
    previewAlt: 'fireworks-ai-tools-memory README 中的产品主视觉',
    previewSource: 'README visual: Tool memory workspace',
    previewFit: 'cover',
    highlights: ['CLI 经验沉淀', '工具知识库', '可检索工作流'],
    description:
      '面向 AI 工具、CLI 工作流和可复用脚本的跨会话记忆层，沉淀工具使用经验。',
    url: 'https://github.com/yizhiyanhua-ai/fireworks-ai-tools-memory',
    demo: 'https://yizhiyanhua-ai.github.io/fireworks-ai-tools-memory/',
    stars: 0,
    forks: 0,
    language: 'HTML',
    tags: ['Automation', 'CLI', 'Knowledge base'],
    accent: 'gold',
  },
  {
    name: 'media-downloader',
    category: 'AI 内容生产',
    productType: 'Media Workflow AI',
    tagline: '内容生产前置素材引擎',
    useCase: '素材搜索 / 图片视频下载 / 内容创作',
    outcome: '用描述驱动素材收集，把内容生产前期的搜索、筛选和下载流程自动化。',
    launchRank: '#5',
    upvotes: '391',
    previewType: 'media',
    previewImage: '/fireworks/assets/product-media-downloader-repo.png',
    previewAlt: 'media-downloader 的 GitHub 仓库公开预览卡',
    previewSource: 'GitHub repository preview',
    highlights: ['描述驱动搜索', '图片视频下载', '创作素材管线'],
    description:
      '根据描述自动搜索和下载图片、视频片段，服务内容创作、研究与视觉素材收集。',
    url: 'https://github.com/yizhiyanhua-ai/media-downloader',
    demo: null,
    stars: 391,
    forks: 44,
    language: 'Python',
    tags: ['Media', 'Search', 'Automation'],
    accent: 'orange',
  },
  {
    name: 'skills-updater',
    category: 'AI Agent 工作流',
    productType: 'Skill Registry',
    tagline: 'Agent 技能生态维护器',
    useCase: '技能发现 / 技能更新 / Agent 工具链维护',
    outcome: '让 Claude Code skills 具备可发现、可更新、可维护的生态入口。',
    launchRank: '#6',
    upvotes: '165',
    previewType: 'registry',
    previewImage: '/fireworks/assets/product-skills-updater-repo.png',
    previewAlt: 'skills-updater 的 GitHub 仓库公开预览卡',
    previewSource: 'GitHub repository preview',
    highlights: ['技能发现', '批量更新', '工具链维护'],
    description:
      '管理、更新和发现 Claude Code skills，让社区工具链保持可维护、可迭代。',
    url: 'https://github.com/yizhiyanhua-ai/skills-updater',
    demo: null,
    stars: 166,
    forks: 15,
    language: 'Python',
    tags: ['Skills', 'Registry', 'Updater'],
    accent: 'blue',
  },
  {
    name: 'chuinb-skill',
    category: 'AI 学习与研究',
    productType: 'Industry Learning Agent',
    tagline: '陌生行业的速通研究助手',
    useCase: '行业速成 / 术语拆解 / 产业链研究',
    outcome: '把陌生行业拆成术语、产业链、关键玩家和行动路线，帮助实践者快速进入语境。',
    launchRank: '#7',
    upvotes: '92',
    previewType: 'research',
    previewImage: '/fireworks/assets/product-chuinb-banner.webp',
    previewAlt: 'chuinb-skill README 中的行业速成产品横幅',
    previewSource: 'README visual: Industry Mastery',
    previewFit: 'cover',
    highlights: ['术语拆解', '产业链地图', '行动路线'],
    description:
      '行业速成大师：把陌生行业拆成术语、产业链、关键玩家和行动路线。',
    url: 'https://github.com/yizhiyanhua-ai/chuinb-skill',
    demo: null,
    stars: 91,
    forks: 7,
    language: 'Shell',
    tags: ['Learning', 'Research', 'Claude Code'],
    accent: 'purple',
  },
  {
    name: 'youtube-ai-digest',
    category: 'AI 学习与研究',
    productType: 'Video Research Digest',
    tagline: '把 AI 长视频变成学习资产',
    useCase: 'AI 视频总结 / 学习材料沉淀 / 长内容处理',
    outcome: '把 AI 相关长视频转成结构化摘要和可复用学习材料，连接内容输入和知识沉淀。',
    launchRank: '#8',
    upvotes: '52',
    previewType: 'video',
    previewImage: '/fireworks/assets/product-youtube-digest-repo.png',
    previewAlt: 'youtube-ai-digest 的 GitHub 仓库公开预览卡',
    previewSource: 'GitHub repository preview',
    highlights: ['长视频摘要', '结构化笔记', '学习材料沉淀'],
    description:
      '浏览、总结并捕获 AI 相关 YouTube 视频，把长视频转成可复用的学习材料。',
    url: 'https://github.com/yizhiyanhua-ai/youtube-ai-digest',
    demo: null,
    stars: 52,
    forks: 6,
    language: 'Python',
    tags: ['YouTube', 'Digest', 'AI learning'],
    accent: 'green',
  },
];

export const operatingPrinciples = [
  {
    title: '开源开放',
    body: '优先沉淀可验证、可复用、可 Fork 的项目和方法，让社区成果可以被外部开发者继续使用。',
    tone: 'blue',
  },
  {
    title: '共建共治',
    body: '社区的价值来自真实使用者：提出问题、复盘过程、贡献脚本、修正文档、共同维护质量。',
    tone: 'orange',
  },
  {
    title: '质量优先',
    body: '重视证据、验证和可运行成果，少做口号，多交付能被别人接着用的资产。',
    tone: 'gold',
  },
  {
    title: '长期主义',
    body: '把一次性技巧升级成工具链、Skill、教程和开源项目，让个人学习曲线和社区资产持续复利。',
    tone: 'green',
  },
  {
    title: '安全合规',
    body: '官网只展示公开信息，不展示私密群内容、个人隐私、未授权联系方式或凭据。',
    tone: 'purple',
  },
];

export const rhythm = [
  {
    title: '每周共学',
    detail: '围绕新工具、新论文和工程案例做结构化拆解。',
  },
  {
    title: '论文精读',
    detail: '把关键概念、实验方法和可复现路径整理成社区材料。',
  },
  {
    title: '项目共创',
    detail: '围绕真实需求打磨 Skill、脚本、模板和演示站点。',
  },
  {
    title: '复盘沉淀',
    detail: '把过程、失败、验证结果写进文档和代码，而不只停留在讨论。',
  },
  {
    title: '成果展示',
    detail: '把可公开项目集中到 GitHub Pages 与开源仓库，方便更多人复用。',
  },
];
